name: Tests

on: 
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.10"]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python }}
      - name: Install pytest
        run: python -m pip install pytest
      - name: Install requirements
        run: python -m pip install pandas
      - name: Run pytest
        run: python -m pytest

