name: Tests

on: 
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python: ["3.10"]
        poetry: ["1.2.2"]

    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: ${{ matrix.poetry }}
      - run: poetry config virtualenvs.create false
      - run: poetry install --no-interaction --no-ansi
      - name: Run pytest
        run: poetry run pytest

